name: Welcome

on: [pull_request,workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Hi @${{ github.actor }} :wave: Thank you for proposing your changes and submitting your first pull request as part of the **Git Goals Tutorial**! One of the Start Your Lab team members will review your request soon.'
